# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.edge.service import Service
from selenium.webdriver.support import expected_conditions as EC

class TestTestdeleteproduct():
  def setup_method(self, method):
       service = Service(executable_path="C:/webdriver/msedgedriver.exe")
       self.driver = webdriver.Edge(service=service)
       self.vars = {}
       time.sleep(2) 
  class TestTestlogin:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()


  
  def test_testdeleteproduct(self):
    self.driver.get("http://127.0.0.1:8000/delete-product/15")
    self.driver.set_window_size(1272, 816)
    
    # Attendre que le bouton soit cliquable
    button = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.NAME, "button"))
    )
    button.click()
  time.sleep(3) 