# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.edge.service import Service


class TestAddProduct:
    def setup_method(self, method):
        service = Service(executable_path="C:/webdriver/msedgedriver.exe")
        self.driver = webdriver.Edge(service=service)
        self.driver.implicitly_wait(10)  # Implicit wait for elements
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_add_product(self):
        # Accéder à la page de création de produit
        self.driver.get("http://127.0.0.1:8000/create-product/")
        self.driver.set_window_size(1272, 816)

        # 1. Remplir le champ "Nom du produit"
        product_name_field = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.ID, "id_product_name"))
        )
        product_name_field.click()
        product_name_field.send_keys("Samsung A15")
        time.sleep(2) 
        # 2. Ajouter une image
        image_field = self.driver.find_element(By.ID, "id_image")
        image_field.send_keys("C:\\Users\\nourn\\OneDrive\\Images\\smartwatch.jpg")  # Remplacez par un chemin valide
        time.sleep(2) 
        # 3. Sélectionner une étiquette (tag)
        tags_dropdown = self.driver.find_element(By.ID, "id_tags")
        tags_option = tags_dropdown.find_element(By.XPATH, "//option[. = 'Smartphone']")
        tags_option.click()
        time.sleep(2) 
        # 4. Ajouter une description
        description_field = self.driver.find_element(By.ID, "id_description")
        description_field.click()
        description_field.send_keys("Un smartphone haut de gamme avec écran AMOLED, 128 Go de stockage.")
        time.sleep(2)  
        # 5. Sélectionner une catégorie
        category_dropdown = self.driver.find_element(By.ID, "id_category")
        category_option = category_dropdown.find_element(By.XPATH, "//option[. = 'Electronics']")
        category_option.click()
        time.sleep(2) 
        # 6. Soumettre le formulaire
        submit_button = self.driver.find_element(By.NAME, "button")
        submit_button.click()
        time.sleep(2) 
        # 7. Vérification après soumission (par exemple, redirection ou message de succès)
        WebDriverWait(self.driver, 10).until(
            EC.url_contains("all-product")  # Vérifiez si la redirection fonctionne
        )
